name: Test Secrets

on:
  workflow_dispatch

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Secret Presence
        run: |
          echo "SFTP_HOST: ${{ secrets.SFTP_HOST }}"
          echo "SFTP_PORT: ${{ secrets.SFTP_PORT }}"
          echo "SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}"

          pw="${{ secrets.SFTP_PASSWORD }}"
          echo "SFTP_PASSWORD length: ${#pw}"
